### ISSUE TITLE
安装好了有个默认的登录密码请问是多少啊

### ISSUE THREAD

**Issue by 516300502** [twotreesus/V2ray.FunPi#9]
如题，我没有配置过密码

**Comment by wangaicc** [comment]
https://github.com/twotreesus/V2ray.FunPi#%E4%BF%AE%E6%94%B9%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE

**Comment by twotreeszf** [comment]
admin admin 看文档

**Comment by twotreesus** [comment]
看文档
